# Processes Indelible-related files
import csv
from cStringIO import StringIO
import Bio.Phylo as Phylo


def get_tree_string(tree_txt):
    """
    Parses the trees.txt file autogenerated by indelible.
    ASSUMES:
    - File starts with comments
    - Header: FILE	TREE	NTAXA	REP	PART	LENGTH	DEPTH	MAX PAIRWISE DISTANCE	TREE STRING
    - Contents follow:

    small_population.50.0	bigtree	100	1	1	50	1.1657	2.25102	((((((otu1:0.688568,....)ROOT;

    :param str tree_txt: full filepath of trees.txt file
    :return str:  tree string
    """
    with open(tree_txt, 'rU') as fh_in:
        # Skip the comments
        TOTAL_COMMENTS_LINES = 6
        for i in range(0, TOTAL_COMMENTS_LINES):
            fh_in.next()
        reader = csv.DictReader(fh_in, delimiter="\t")
        for row in reader:
            if not row["FILE"]:
                continue
            return row["TREE STRING"]

    return None


def get_tree_stringio(tree_txt):
    """
    Parses the trees.txt file autogenerated by indelible.
    ASSUMES:
    - File starts with comments
    - Header: FILE	TREE	NTAXA	REP	PART	LENGTH	DEPTH	MAX PAIRWISE DISTANCE	TREE STRING
    - Contents follow:

    small_population.50.0	bigtree	100	1	1	50	1.1657	2.25102	((((((otu1:0.688568,....)ROOT;

    :param str tree_txt: full filepath of trees.txt file
    :return StringIO:  tree string as StringIO handle
    """
    with open(tree_txt, 'rU') as fh_in:
        # Skip the comments
        TOTAL_COMMENTS_LINES = 6
        for i in range(0, TOTAL_COMMENTS_LINES):
            fh_in.next()
        reader = csv.DictReader(fh_in, delimiter="\t")
        for row in reader:
            if not row["FILE"]:
                continue
            return StringIO(row["TREE STRING"])

    return None


def write_tree(tree_txt, tree_newick):
    """
    Parses the trees.txt file autogenerated by indelible.  Writes out tree to a newick file.
    ASSUMES:
    - File starts with comments
    - Header: FILE	TREE	NTAXA	REP	PART	LENGTH	DEPTH	MAX PAIRWISE DISTANCE	TREE STRING
    - Contents follow:

    small_population.50.0	bigtree	100	1	1	50	1.1657	2.25102	((((((otu1:0.688568,....)ROOT;

    :param str tree_txt: full filepath of trees.txt file
    :param str tree_newick:  full filepath of newick file to write out.
    """
    with open(tree_txt, 'rU') as fh_in, open(tree_newick, 'w') as fh_out:
        # Skip the comments
        TOTAL_COMMENTS_LINES = 6
        for i in range(0, TOTAL_COMMENTS_LINES):
            fh_in.next()
        reader = csv.DictReader(fh_in, delimiter="\t")
        for row in reader:
            if not row["FILE"]:
                continue
            tree_str = row["TREE STRING"]
            fh_out.write(tree_str)
            break



