# Processes Indelible-related files
import csv
from Bio import Phylo
from Bio import SeqIO as SeqIO
from Bio import Seq as Seq
from cStringIO import StringIO
import itertools
import Utility


def get_tree_string(tree_txt):
    """
    Parses the trees.txt file autogenerated by indelible.
    ASSUMES:
    - File starts with comments
    - Header: FILE	TREE	NTAXA	REP	PART	LENGTH	DEPTH	MAX PAIRWISE DISTANCE	TREE STRING
    - Contents follow:

    small_population.50.0	bigtree	100	1	1	50	1.1657	2.25102	((((((otu1:0.688568,....)ROOT;

    :param str tree_txt: full filepath of trees.txt file
    :return str:  tree string
    """
    with open(tree_txt, 'rU') as fh_in:
        # Skip the comments
        TOTAL_COMMENTS_LINES = 6
        for i in range(0, TOTAL_COMMENTS_LINES):
            fh_in.next()
        reader = csv.DictReader(fh_in, delimiter="\t")
        for row in reader:
            if not row["FILE"]:
                continue
            return row["TREE STRING"]

    return None
